# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Delbra < Formula
  desc "CLI to delete multiple local Git branches at once"
  homepage "https://github.com/okradze/delbra"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okradze/delbra/releases/download/v0.0.4/delbra_Darwin_x86_64.tar.gz"
      sha256 "3868d0cef87363947d03dc9461fe66a0270eace72004e0a210b4a2ec7ac0e08f"

      def install
        bin.install "delbra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okradze/delbra/releases/download/v0.0.4/delbra_Darwin_arm64.tar.gz"
      sha256 "a4c6ec2f6efa49a00c7e15bc6360b4f6a7ff915e51ee934132bca38712178345"

      def install
        bin.install "delbra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/okradze/delbra/releases/download/v0.0.4/delbra_Linux_x86_64.tar.gz"
      sha256 "b11cd31f31a0a83567add7603750d5107dc45c2480d7379070b6370968b1b9c2"

      def install
        bin.install "delbra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okradze/delbra/releases/download/v0.0.4/delbra_Linux_arm64.tar.gz"
      sha256 "93334c732619b04fd19b70383bdcd79350fe95c86da186ad556614f525423ca1"

      def install
        bin.install "delbra"
      end
    end
  end
end
