# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Delbra < Formula
  desc "CLI to delete multiple local Git branches at once"
  homepage "https://github.com/okradze/delbra"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okradze/delbra/releases/download/v0.0.3/delbra_Darwin_x86_64.tar.gz"
      sha256 "2ece794cf24af0320c2844fb869d18cd80a37d70f5fce01cfe339e8ff49a6d1d"

      def install
        bin.install "delbra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okradze/delbra/releases/download/v0.0.3/delbra_Darwin_arm64.tar.gz"
      sha256 "628f21dcedbe3179eef779c89b931fa5a8aac506a5a037134ed40d15c287209b"

      def install
        bin.install "delbra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/okradze/delbra/releases/download/v0.0.3/delbra_Linux_x86_64.tar.gz"
      sha256 "629a9e2246911d9aef99fcbfe12c9ff77daa593547031263f65d04fbbdfd3bb5"

      def install
        bin.install "delbra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okradze/delbra/releases/download/v0.0.3/delbra_Linux_arm64.tar.gz"
      sha256 "e6de0049209a0d7b0722c9453f573b48a70301303ed95c8f7088cb355a88075d"

      def install
        bin.install "delbra"
      end
    end
  end
end
